namespace: mihudec

name: net_filters

version: 1.0.0


readme: README.md

authors:
- Miroslav Hudec <https://github.com/mihudec>


description: Collection of Jinja2 filters for networking playbooks

license:
- GPL-2.0-or-later

license_file: ''

tags: []

dependencies: {}

repository: https://github.com/mihudec/net_filters

documentation: https://github.com/mihudec/net_filters

homepage: https://github.com/mihudec/net_filters

issues: https://github.com/mihudec/net_filters

build_ignore: []

