name: Upload Collection to Galaxy
on:
  release:
    types: [created]
jobs:
  build:
    name: Build Collection
    env:
      AUTHOR: mihudec
      COLLECTION_NAME: net_filters
    runs-on: ubuntu-latest

    steps:
      - name: Create Collections Directory
        run: |
          mkdir -p ansible_collections/${{ env.AUTHOR }}
      
      - name: Checkout net_filters
        uses: actions/checkout@v2
        with:
          path: ansible_collections/${{ env.AUTHOR }}

      - name: Display Directory Tree
        run: |
          tree ansible_collections      

      - name: Install Pip and Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      
      - name: Build Collection
        run: |
          cd ansible_collections/${{ env.AUTHOR }}/${{ env.COLLECTION_NAME }}
          echo ARCHIVE_PATH=$(ansible-galaxy collection build --force | awk -F' ' '{print $6}') >> $GITHUB_ENV
          echo ${{ env.ARCHIVE_PATH }}

      - name: Upload to Galaxy
        run: |
          ansible-galaxy collection publish \
          ${{ env.ARCHIVE_PATH }} \
          --token ${{ secrets.ANSIBLE_GALAXY_TOKEN }}